service: app

provider:
    name: aws
    region: us-east-1

plugins:
    - ./vendor/bref/bref
    - ./vendor/bref/extra-php-extensions

functions:
    api:
        handler: index.php
        description: ''
        runtime: php-81
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   httpApi: '*'
    console:
        handler: bin/console
        runtime: php-81
        layers:
            - ${bref-extra:mongodb-php-81}

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
